### ISSUE TITLE
Get this built today

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#93]
I'm trying to build this (to disable tree deletion), basically using `npm ci && npm run-script-build`. I'm trying different node and npm version, but it just fails in the end with:

```
 ERROR  Failed to compile with 1 error                                                                                                              11:30:04 AM

 error  in ./src/App.vue

Syntax Error: TypeError: Cannot read property 'parseComponent' of undefined
```

:exploding_head: 

This last try was for example on node 15 with npm 7 (v7 seems to have last produces the `package-lock.json` which has `"lockFileVersion": 2`).  Do you have any working combination @rotsee

**Comment by rotsee** [comment]
I pushed some updates to package.json now, to add explicit and exact package version numbers. 

If that still doesn't work, try:
```
rm package-lock.json
rm -rf node_modules/*
npm install
npm run serve
```

**Comment by quite** [comment]
No, i can neither build nor serve, clean build doesn't help. Tried also node 18, 20 with corresponding npm. I'm using https://github.com/tj/n

```

> fruktkartan@0.2.0 serve
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/5 modules 3 active /home/quite/src/fruktkartan/frontend/node_modules/webpack/hot/dev-server.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/home/quite/src/fruktkartan/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/quite/src/fruktkartan/frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/quite/src/fruktkartan/frontend/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/quite/src/fruktkartan/frontend/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/quite/src/fruktkartan/frontend/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/quite/src/fruktkartan/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/quite/src/fruktkartan/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/quite/src/fruktkartan/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/quite/src/fruktkartan/frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/quite/src/fruktkartan/frontend/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/quite/src/fruktkartan/frontend/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/quite/src/fruktkartan/frontend/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/quite/src/fruktkartan/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/quite/src/fruktkartan/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/home/quite/src/fruktkartan/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/quite/src/fruktkartan/frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/quite/src/fruktkartan/frontend/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/quite/src/fruktkartan/frontend/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/quite/src/fruktkartan/frontend/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/quite/src/fruktkartan/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/quite/src/fruktkartan/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/quite/src/fruktkartan/frontend/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/quite/src/fruktkartan/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/quite/src/fruktkartan/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/quite/src/fruktkartan/frontend/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.5.1
```

Think I need exact same environment as you have :-D

Also your latest commit made something out of sync regarding package{,-lock}.json think, `npm ci` now complains.

**Comment by rotsee** [comment]
Right, to make it run on Node 19+ you will have to do `NODE_OPTIONS=--openssl-legacy-provider npm run serve
`, allowing some older, less safe SSL crypto stuff

**Comment by quite** [comment]
Thanks! I managed to get it built with that. I've fixed up the github actions and netlify builds, and also removed the delete-tree button (https://github.com/fruktkartan/fruktkartan-api/issues/14). It's all pushed to master, which you may try out here: https://master--fruktkartan.netlify.app -- if it looks good you/I can merge to production branch.

**Comment by rotsee** [comment]
Wonderful, thanks for finding time for this!
